### PR TITLE
fix: a schema using allOf, with a reference to another schema, should create a subclass

### LINKED ISSUE #66: Generation of java code for 'allOff' modifier doesn't generates descendant class
#### Describe the bug
Generation of java code for 'allOff' modifier doesn't generates descendant class as for Inheritance so Composition

#### How to Reproduce
Using configuration in schemas like this produces only ErrorModel class
<pre>
    ErrorModel:
      type: object
      required:
      - message
      - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedErrorModel:
      allOf:
      - $ref: '#/components/schemas/ErrorModel'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string
</pre>
  
#### Expected behavior
Must be generated ErrorModel.java and ExtendedErrorModel.java

### PR DESCRIPTION
**Pull request by damaru-inc**
**Description**

See issue #66 for an example of how a schema can subclass another schema. This adds support for this case.

Note that it is a fairly large code change, because it is now necessary to preprocess all the schemas to determine when one is a subclass of another.

**Related issue(s)**
Fixes #66

### CODE REVIEW

File: partials/java-class [hunk 1]
```diff
@@ -1,15 +1,18 @@
-{%- macro javaClass(name, schema, properties, required, indentLevel, isStatic) %}
```
Comment (CameronRushton) [inline partials/java-class:1]: What happened to required? Was it dead code?

File: lib/applicationModel.js [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+    if (!this.superClassMap) {
+      this.superClassMap = new Map();
+      this.anonymousSchemaToSubClassMap = new Map();
+      debugApplicationModel('-------- SCHEMAS -------------');
+      debugApplicationModel(ApplicationModel.asyncapi.allSchemas());
+      ApplicationModel.asyncapi.allSchemas().forEach((schema, schemaName) => {
+        debugApplicationModel(`${schemaName}:`);
+        debugApplicationModel(schema);
+        const allOf = schema.allOf();
+        if (allOf) {
```
Comment (CameronRushton) [inline lib/applicationModel.js:41]: What's the plan for related keywords like anyOf, oneOf, and not? Something to implement later? I dont wanna scope creep but it would seem odd as a user.

File: lib/applicationModel.js [hunk 3]
```diff
@@ -0,0 +1,135 @@
...
+        debugApplicationModel(`setupModelClassMap ${schemaName} type ${schema.type()}`);
+        const allOf = schema.allOf();
+        debugApplicationModel('allOf:');
+        debugApplicationModel(allOf);
+        if (allOf) {
+          allOf.forEach(innerSchema => {
+            const name = innerSchema._json['x-parser-schema-id'];
+            if (this.isAnonymousSchema(name) && innerSchema.type() === 'object') {
+              this.addSchemaToMap(innerSchema, schemaName);
+            }
```
Comment (CameronRushton) [inline lib/applicationModel.js:85]: I'm worried about schema.type() being 'object' but not the kind of object we expect. I'd assume the parser does something to make sure it's the right thing, though. typeof null === 'object', typeof [] === 'object', etc...

File: partials/java-class (hunk 1 above)
Comment (damaru-inc) [reply partials/java-class:1]: Yes, I never used the 'required' parameter.

File: lib/applicationModel.js (hunk 2 above)
Comment (damaru-inc) [reply lib/applicationModel.js:37]: I'll address those as people request them.

File: lib/applicationModel.js (hunk 3 above)
Comment (damaru-inc) [reply lib/applicationModel.js:85]: That's a good point. So far I haven't seen any problems with this, but I'll review the parser-js code to make sure.

Comment (CameronRushton) [reply lib/applicationModel.js:85]: Oh this type is a json schema type, so that could include string, number, integer, object, array, boolean, and null. If the schema type is an array, for example, would we still want a class for it? I think it would be different. So leaving it to do its thing with just 'object' is good enough. Dont want to scope creep.

File: hooks/post-process.js [hunk 4]
```diff
@@ -58,67 +31,104 @@ module.exports = {
...
+function getFileName(schemaName) {
+  const trimmedSchemaName = trimSchemaName(schemaName);
+  return `${trimmedSchemaName}.java`;
+}
+
+function trimSchemaName(schemaName) {
+  let trimmedSchemaName = schemaName;
+  if (schemaName.startsWith('<')) {
+    trimmedSchemaName = schemaName.replace('<', '');
+    trimmedSchemaName = trimmedSchemaName.replace('>', '');
```
Comment (CameronRushton) [inline hooks/post-process.js:110]: It looks like it may be possible for a schema name to have angle brackets as part of the name according to the playground. Pretty sure replace starts from the left, so maybe the second replace would need to use a regex with `$` so `('/>$/', '')` with it properly escaped if needed

**Review by CameronRushton — DISMISSED** [review]
No further comments from me. I'll leave it to you

File: hooks/post-process.js (hunk 4 above)
Comment (damaru-inc) [reply hooks/post-process.js:110]: Good catch, I'll definitely improve that.

**Comment by derberg** [comment]
No comments from my side folks, lgtm. Once @CameronRushton approves, I'll also approve and you can merge.

**Review by CameronRushton — APPROVED** [review]

**Review by derberg — APPROVED** [review]
