### PR TITLE
fix: template uses anonymous schema name when object type is unknown

### LINKED ISSUE #288: Generator produces Java code with `&lt;anonymous-schema-6&gt;` Object types
Hi there.  I have a fairly (?) complicated JSON event schema, and it causes the generated code to have:
```
        public MessageVpn010 (
                Boolean isManagementMessageVpn,
                &lt;anonymous-schema-2&gt; messageSpoolStats,
                String radiusDomain,
                Boolean operational,
                Boolean enabled,
                &lt;anonymous-schema-6&gt; subscriptionTable,
                &lt;anonymous-schema-7&gt; stats,
                Boolean distributedCacheManagementEnabled,
```

I've attached my AsyncAPI schema file. Huh, doesn't support JSON files.  I'll just inline:

```
{"components":{"schemas":{"Message VPN_0_1_0":{"x-ep-schema-version":"0.1.0","x-ep-schema-state-id":"1","x-ep-schema-version-id":"uvkail7pnsb","x-ep-schema-id":"pvexikfs755","x-ep-schema-state-name":"DRAFT","x-ep-schema-name":"Message VPN","type":"object","title":"/rpc-reply/rpc/show/message-vpn/vpn","properties":{"isManagementMessageVpn":{"type":"boolean"},"messageSpoolStats":{"qendptUnbindStats":{"unbindResponses":{"format":"int64","type":"integer","minimum":0},"failNotFound":{"format":"int64","type":"integer","minimum":0},"unbindRequests":{"format":"int64","type":"integer","minimum":0},"failOther":{"format":"int64","type":"integer","minimum":0},"okResponse":{"format":"int64","type":"integer","minimum":0}},"publisherOpenStats":{"failDeniedGuaranteedMessages":{"format":"int64","type":"integer","minimum":0},"failExceededClients":{"format":"int64","type":"integer","minimum":0},"responses":{"format":"int64","type":"integer","minimum":0},"requests":{"format":"int64","type":"integer","minimum":0},"failOther":{"format":"int64","type":"integer","minimum":0},"okResponse":{"format":"int64","type":"integer","minimum":0}},"qendptBindStats":{"failInvalidSelector":{"format":"int64","type":"integer","minimum":0},"failDeniedGuaranteedMessages":{"format":"int64","type":"integer","minimum":0},"bindResponses":{"format":"int64","type":"integer","minimum":0},"bindRequests":{"format":"int64","type":"integer","minimum":0},"failShutdown":{"format":"int64","type":"integer","minimum":0},"failAlreadyBound":{"format":"int64","type":"integer","minimum":0},"failExceededClients":{"format":"int64","type":"integer","minimum":0},"failOther":{"format":"int64","type":"integer","minimum":0},"okResponse":{"format":"int64","type":"integer","minimum":0}}},"radiusDomain":{"type":"string"},"operational":{"type":"boolean"},"enabled":{"type":"boolean"},"subscriptionTable":{"subscriptionEntry":[{"sequenceNum":{"format":"int64","type":"integer","minimum":0},"destinations":{"format":"int64","type":"integer"},"subscription":{"type":"string"},"redundancyType":{"type":"string"}}]},"stats":{"clientNonPersistentMessagesReceived":{"format":"int64","type":"integer"},"clientDirectMessagesSent":{"format":"int64","type":"integer"},"deniedDuplicateClients":{"format":"int64","type":"integer"},"clientControlMessagesReceived":{"format":"int64","type":"integer"},"clientDataMessagesReceived":{"format":"int64","type":"integer"},"clientDataMessagesSent":{"format":"int64","type":"integer"},"loginMsgsReceived":{"format":"int64","type":"integer"},"clientDataBytesPersistentSent":{"format":"int64","type":"integer"},"averageEgressByteRatePerMinute":{"format":"int64","type":"integer"},"averageIngressByteRatePerMinute":{"format":"int64","type":"integer"},"clientDataBytesDirectSent":{"format":"int64","type":"integer"},"averageIngressRatePerMinute":{"format":"int64","type":"integer"},"updateMsgsReceived":{"format":"int64","type":"integer"},"currentEgressByteRatePerSecond":{"format":"int64","type":"integer"},"totalClientBytesReceived":{"format":"int64","type":"integer"},"keepaliveMsgsSent":{"format":"int64","type":"integer"},"notEnoughSpaceMsgsSent":{"format":"int64","type":"integer"},"parseErrorOnRemoveMsgsSent":{"format":"int64","type":"integer"},"deniedSubscribeTopicAcl":{"format":"int64","type":"integer"},"deniedSubscribePermission":{"format":"int64","type":"integer"},"totalClientsConnected":{"format":"int64","type":"integer"},"clientPersistentMessagesSent":{"format":"int64","type":"integer"},"dtoMessagesReceived":{"format":"int64","type":"integer"},"clientNonPersistentBytesSent":{"format":"int64","type":"integer"},"largeMessagesReceived":{"format":"int64","type":"integer"},"assuredCtrlMsgsReceived":{"format":"int64","type":"integer"},"clientNonPersistentBytesReceived":{"format":"int64","type":"integer"},"clientDataBytesSent":{"format":"int64","type":"integer"},"currentIngressByteRatePerSecond":{"format":"int64","type":"integer"},"unsubscribeClientNotFound":{"format":"int64","type":"integer"},"removeSubscriptionManagerMsgsReceived":{"format":"int64","type":"integer"},"clientPersistentMessagesReceived":{"format":"int64","type":"integer"},"notFoundMsgsSent":{"format":"int64","type":"integer"},"deniedUnsubscribeTopicAcl":{"format":"int64","type":"integer"},"clientDataBytesReceived":{"format":"int64","type":"integer"},"removeSubscriptionManagerMsgsSent":{"format":"int64","type":"integer"},"deniedAuthorizationFailed":{"format":"int64","type":"integer"},"subscribeClientNotFound":{"format":"int64","type":"integer"},"addSubscriptionMsgsReceived":{"format":"int64","type":"integer"},"clientPersistentBytesReceived":{"format":"int64","type":"integer"},"clientControlBytesSent":{"format":"int64","type":"integer"},"egressDiscards":{"messageElided":{"format":"int64","type":"integer"},"msgSpoolEgressDiscards":{"format":"int64","type":"integer"},"messagePromotionCongestion":{"format":"int64","type":"integer"},"transmitCongestion":{"format":"int64","type":"integer"},"compressionCongestion":{"format":"int64","type":"integer"},"totalEgressDiscards":{"format":"int64","type":"integer"}},"removeSubscriptionMsgsReceived":{"format":"int64","type":"integer"},"clientDataBytesPersistentReceived":{"format":"int64","type":"integer"},"totalClientsConnectedWithCompression":{"format":"int64","type":"integer"},"alreadyExistsMsgsSent":{"format":"int64","type":"integer"},"clientPersistentBytesSent":{"format":"int64","type":"integer"},"clientControlBytesReceived":{"format":"int64","type":"integer"},"totalClientMessagesReceived":{"format":"int64","type":"integer"},"updateMsgsSent":{"format":"int64","type":"integer"},"keepaliveMsgsReceived":{"format":"int64","type":"integer"},"zipStats":{"ingressCompressedBytes":{"format":"int64","type":"integer"},"currentIngressCompressedRatePerSecond":{"format":"int64","type":"integer"},"currentEgressCompressedRatePerSecond":{"format":"int64","type":"integer"},"egressCompressedBytes":{"format":"int64","type":"integer"},"ingressCompressionRatio":{"format":"float","type":"number"},"averageIngressUncompressedRatePerMinute":{"format":"int64","type":"integer"},"ingressUncompressedBytes":{"format":"int64","type":"integer"},"decompressErrorCount":{"format":"int64","type":"integer"},"egressUncompressedBytes":{"format":"int64","type":"integer"},"averageIngressCompressedRatePerMinute":{"format":"int64","type":"integer"},"currentIngressUncompressedRatePerSecond":{"format":"int64","type":"integer"},"averageEgressUncompressedRatePerMinute":{"format":"int64","type":"integer"},"currentEgressUncompressedRatePerSecond":{"format":"int64","type":"integer"},"averageEgressCompressedRatePerMinute":{"format":"int64","type":"integer"},"egressCompressionRatio":{"format":"float","type":"number"},"compressErrorCount":{"format":"int64","type":"integer"}},"maxExceededMsgsSent":{"format":"int64","type":"integer"},"averageEgressRatePerMinute":{"format":"int64","type":"integer"},"ingressDiscards":{"topicParseError":{"format":"int64","type":"integer"},"publishTopicAcl":{"format":"int64","type":"integer"},"parseError":{"format":"int64","type":"integer"},"noSubscriptionMatch":{"format":"int64","type":"integer"},"msgSpoolDiscards":{"format":"int64","type":"integer"},"totalIngressDiscards":{"format":"int64","type":"integer"},"ttlExceeded":{"format":"int64","type":"integer"},"msgTooBig":{"format":"int64","type":"integer"}},"totalClientMessagesSent":{"format":"int64","type":"integer"},"clientNonPersistentMessagesSent":{"format":"int64","type":"integer"},"addSubscriptionManagerMsgsSent":{"format":"int64","type":"integer"},"ingressCompressedBytes":{"format":"int64","type":"integer"},"deniedUnsubscribePermission":{"format":"int64","type":"integer"},"clientDataBytesDirectReceived":{"format":"int64","type":"integer"},"clientDirectBytesReceived":{"format":"int64","type":"integer"},"egressCompressedBytes":{"format":"int64","type":"integer"},"clientDataBytesNonPersistentReceived":{"format":"int64","type":"integer"},"addSubscriptionMsgsSent":{"format":"int64","type":"integer"},"managedSubscriptions":{"addBySubscriptionManager":{"format":"int64","type":"integer"},"removeBySubscriptionManager":{"format":"int64","type":"integer"}},"loginMsgsSent":{"format":"int64","type":"integer"},"clientDirectMessagesReceived":{"format":"int64","type":"integer"},"clientControlMessagesSent":{"format":"int64","type":"integer"},"parseErrorOnAddMsgsSent":{"format":"int64","type":"integer"},"addSubscriptionManagerMsgsReceived":{"format":"int64","type":"integer"},"currentEgressRatePerSecond":{"format":"int64","type":"integer"},"clientDirectBytesSent":{"format":"int64","type":"integer"},"clientDataBytesNonPersistentSent":{"format":"int64","type":"integer"},"deniedClientConnectAcl":{"format":"int64","type":"integer"},"totalClientBytesSent":{"format":"int64","type":"integer"},"removeSubscriptionMsgsSent":{"format":"int64","type":"integer"},"currentIngressRatePerSecond":{"format":"int64","type":"integer"},"assuredCtrlMsgsSent":{"format":"int64","type":"integer"}},"distributedCacheManagementEnabled":{"type":"boolean"},"totalUniqueSubscriptions":{"format":"int64","type":"integer","minimum":0},"name":{"type":"string"},"locallyConfigured":{"type":"boolean"},"maxSubscriptions":{"format":"int64","type":"integer","minimum":0},"authType":{"type":"string"},"eventConfiguration":{"largeMessageThreshold":{"format":"int64","type":"integer","minimum":0},"eventLogTag":{"type":"string"},"publishMessageVpnEventMessagesEnabled":{"type":"boolean"},"publishClientEventMessagesEnabled":{"type":"boolean"},"publishSubscriptionEventMessagesEnabledNoUnsubscribeEventsOnDisconnect":{"type":"boolean"},"publishSubscriptionEventMessagesEnabled":{"type":"boolean"},"eventThresholds":[{"clearPercentage":{"format":"int64","type":"integer","minimum":0},"setValue":{"format":"int64","type":"integer","minimum":0},"name":{"type":"string"},"clearValue":{"format":"int64","type":"integer","minimum":0},"setPercentage":{"format":"int64","type":"integer","minimum":0}}]},"uniqueSubscriptions":{"format":"int64","type":"integer","minimum":0},"authProfile":{"type":"string"},"totalRemoteUniqueSubscriptions":{"format":"int64","type":"integer","minimum":0},"connections":{"format":"int64","type":"integer","minimum":0},"maximumSpoolUsageMb":{"format":"int64","type":"integer","minimum":0},"totalLocalUniqueSubscriptions":{"format":"int64","type":"integer","minimum":0},"maxConnections":{"format":"int64","type":"integer","minimum":0}},"x-ep-schema-version-displayname":""}},"messages":{"ShowMessageVPN_0_1_0":{"x-ep-event-id":"5vcfxpgds8l","x-ep-event-version-displayname":"","x-ep-event-version-id":"kb0183jdx7j","payload":{"$ref":"#/components/schemas/Message VPN_0_1_0"},"x-ep-event-version":"0.1.0","x-ep-event-name":"ShowMessageVPN","description":"Returns Message-VPN stats and info.  This is versoin 0.1.0.  And it is shared (at the Event level)","schemaFormat":"application/vnd.aai.asyncapi+json;version=2.0.0","contentType":"application/json","x-ep-event-state-id":"1","x-ep-event-state-name":"DRAFT"}}},"channels":{"pump/vpn/broker/vpnname/detail":{"publish":{"message":{"$ref":"#/components/messages/ShowMessageVPN_0_1_0"}}}},"asyncapi":"2.0.0","info":{"x-ep-application-version-id":"hl0gpuvmzsh","description":"## This is going to be a test of the formatting\nThis first long description is what I really want to test.  Will it work with my text box formatting?  I don't believe so.  Maybe we cna have a popup or something?\n- Here is a list\n- Here is some more lists\n- Last entry\n\nFinally, I'm going to include a code block:\n```\nThis is in a code block.  This is what I'm working on right now:\n\t\t@Override\n\t\tpublic @Nullable TableCellRenderer getRenderer(GenericAppsTableDomain item) {\n\t\t\tTableCellRenderer renderer = super.getRenderer(item);\n//\t\t\trenderer.getTableCellRendererComponent(null, renderer, isSortable(), isSortable(), getAdditionalWidth(), getAdditionalWidth())\n\t\t\t\n\t\t\treturn renderer;\n\t\t}\n```\n","x-ep-displayname":"First Cut","x-ep-state-name":"DRAFT","title":"MessageVpnStatsReceiver","x-ep-application-domain-id":"x4oo4skfh5e","version":"0.1.0","x-ep-state-id":"1","x-ep-application-domain-name":"Aaron Test 1"}}
```

Thanks!

### PR DESCRIPTION
**Pull request by CameronRushton**
**Description**

Throw error when schema type is unknown instead of setting to the x-schema-parser-id.

This doesn't break the functionality of setting $ref for a referenced schema (that doesn't have type set)
Given
```
"components": {
    "schemas": {
      "FelineSchema": {
        "type": "object",
        "properties": {
          "canMeow": {
            "$ref": "#/components/schemas/CatSchema"
          }
        }
      },
      "CatSchema": {
        "type": "object",
        "properties": {
          "meow": {
            "type": "integer"
          }
        }
      }
    }
  }
```
'canMeow' doesn't have a type but that's okay because in the modelClass mapping, we said that canMeow maps to the CatSchema object which does have a type so we get the following correct result with CatSchema defined in its own file.
```
@JsonInclude(JsonInclude.Include.NON_NULL)
public class FelineSchema {

	public FelineSchema () {
	}

	public FelineSchema (
		CatSchema catSchema) {
		this.catSchema = catSchema;
	}

	@JsonProperty("canMeow")
	private CatSchema catSchema;
	
	public CatSchema getCatSchema() {
		return catSchema;
	}

	public FelineSchema setCatSchema(CatSchema catSchema) {
		this.catSchema = catSchema;
		return this;
	}

	public String toString() {
		return "FelineSchema ["
		+ " catSchema: " + catSchema
		+ " ]";
	}
}
```

**Related issue(s)**
Resolves #288

### CODE REVIEW

File: filters/all.js [hunk 1]
```diff
@@ -340,12 +340,7 @@ function fixType([name, javaName, property]) {
       // Picking a type for the user may be difficult - especially since the first avro union value must be the default value which is normally of type null.
       typeName = 'Object';
     } else {
-      // check to see if it's a ref to another schema.
-      typeName = property.ext('x-parser-schema-id');
-
-      if (!typeName) {
-        throw new Error(`Can't determine the type of property ${  name}`);
-      }
+      throw new Error(`Can't determine the type of property ${  name  }`);
```
Comment (CameronRushton) [inline filters/all.js:343]: We could assume it's an object and the class name derived from the model class mapping is correct with
`typeName = javaName;` but it may not always be true. The model class mapping takes the x-schema-parser-id into account when determining the class name so `typeName = javaName` here should be the same idea. However, we'd only do this if we're okay with guessing the type.
If we do guess, this error here would never be thrown because (I think) there is always an x-parser-schema-id present.

**Review by MichaelDavisSolace — APPROVED** [review]

**Review by damaru-inc — APPROVED** [review]
