### PR TITLE
fix:  generation fails when schemas have an $id field or array of objects

### LINKED ISSUE #208: Generation fails when schemas have an $Id field.
#### Describe the bug
Generation fails when schemas have an $Id field.

#### How to Reproduce
Run the generator with the attached file, see the error messages.

#### Expected behavior
The file is valid and should work (I renamed it to .txt so it could be attached.)
[asyncapi.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/7514254/asyncapi.txt)

### LINKED ISSUE #228: [v0.11.5] Code generation fails when object has property named 'size'
#### Describe the bug
Using this generator version 0.11.5, when attempting to generate code for a message that has a field named `size`, the code generation fails.

Version 0.11.4 works.

The error:
```
Something went wrong:
Template render error: (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/template/src/main/java/$$everySchema$$.java)
  TypeError: Cannot set property size of #<Map> which has only a getter
    at Object._prettifyError (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:563:19
    at eval (eval at _compile (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:46:11)
    at /opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:613:9
    at eval (eval at _compile (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:12:11)
    at /opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:613:9
    at Template.root [as rootRenderFunc] (eval at _compile (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:367:3)
    at Template.getExported (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:611:10)
    at eval (eval at _compile (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:11:5)
    at createTemplate (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:315:9)
    at handle (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:327:11)
    at /opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:339:9
    at next (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:328:7)
    at Object.asyncIter (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:334:3)
    at Environment.getTemplate (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:321:9)
    at Template.root [as rootRenderFunc] (eval at _compile (/opt/homebrew/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:9:5)
```

#### How to Reproduce
The following schema produces the error:

```yml
asyncapi: 2.2.0
info:
  title: Amazing Service
  version: 1.0.0
channels:
  /amazingness:
    publish:
      message:
        name: My Amazing Message
        payload:
          type: object
          properties:
            size:
              type: integer
```

Generate using:
```ag <SCHEMA> @asyncapi/java-spring-cloud-stream-template -o <DIR>```

#### Expected behavior
Code generation should just work!

#### Workaround
Fall-back to previous version (0.11.4):
```ag <SCHEMA> @asyncapi/java-spring-cloud-stream-template@v0.11.4 -o <DIR>```

### PR DESCRIPTION
**Pull request by CameronRushton**
**Description**

 $id is now being handled by changing the value to the classname where appropriate as part of the preprocess hook.
Previously, we had a problem with the $id keyword in schemas, where the generator is going to create file names with (and generally favour relying on) a schema's $id keyword if it's set. This causes problems in our code generator because we generally rely on x-parser-schema-id to know the difference between anonymous schemas and schemas that need a class generated for them and in general, we don't use the $id in any way because it's inconsistent and doesn't contain any data that we can definitely rely on to write class names. Since the generator had insisted on using $id, the easiest option for us was to remove the $id fields from all the schemas as part of the preprocess hook. Then, the generator won't use the $id and neither will we.
This didn't fully solve the problem and unknowingly caused another issue where duplicate schemas (i.e. schemas with the same $id which is unfortunately, still a valid schema) werent being changed after removing the $id field. When we retrieve all schemas via generator.asyncapi.allSchemas(), it filters out duplicates naturally because it's backed by a Map. This means deleting the $id of a schema doesn't delete the $id of all the duplicates with the same $id, which brings us back to the same problem with $id.

It would be best to refactor most of our code to work with the generator more using $id, but instead, it's more cost efficient to continually rename the $id of each schema returned to the desired class name until there are no more changes. Then, all the classes are created correctly with the correct names and there are no problems.

===========================

Another bug that is related to this fix, or perhaps blocked by (either way, both fixes are in this PR) is the inability to create a class for a field in a schema that is an array of objects.
Now that all the schemas are correctly present with the $id bug resolved, the name of the class would be incorrect because we have two schemas to use for this one class.
We have the parent schema that has the items keyword. We use this schema as the name of the class.
We also have the anonymous schema for each object in the items keyword. We use this schema as the fields of the class.
There's a new flag that's set up in the pre-process hook for this particular case that is used to rename the class to the parent when creating the ModelClass, so there will be two classes with the same name, but only one is generated as a real class because it has properties. Two different keys (e.g. Payment & PaymentItems) so we can distinguish them, but the same class name (e.g. Payment).

If both parent and items are objects (previously, we were talking about the parent being an array) and the objects have properties, their class names would be the same and that would be a problem. Since items is a validation keyword as opposed to a core keyword, it is ignored in favour of the properties defined by the parent and only the parent's class, with whatever properties it has, is generated.

**Related issue(s)**
Fixes #208 and fixes #228

### CODE REVIEW

File: lib/applicationModel.js [hunk 1]
```diff
@@ -42,25 +42,26 @@ class ApplicationModel {
...
-          this.handleAllOfSchema(schema, schemaName, allOf);
-        }
-      });
-      debugApplicationModel('-----------------------------');
-      debugApplicationModel('superclassMap:');
-      debugApplicationModel(this.superClassMap);
-      debugApplicationModel('anonymousSchemaToSubClassMap:');
-      debugApplicationModel(this.anonymousSchemaToSubClassMap);
+    if (this.superClassMap) {
+      return;
```
Comment (CameronRushton) [inline lib/applicationModel.js:46]: All I did was change this conditional from
```
if (!condition) { runCode }
```
to
```
if (condition) { return }
runCode
```

File: lib/applicationModel.js [hunk 2]
```diff
@@ -89,54 +90,19 @@ class ApplicationModel {
...
-    debugApplicationModel(allOf);
-    if (allOf) {
-      allOf.forEach(innerSchema => {
-        const name = innerSchema.ext('x-parser-schema-id');
-        if (this.isAnonymousSchema(name) && innerSchema.type() === 'object') {
-          this.registerSchemaNameToModelClass(innerSchema, name);
-        }
-      });
+    if (this.modelClassMap) {
+      return;
```
Comment (CameronRushton) [inline lib/applicationModel.js:94]: Same idea with the conditional changed from the code being nested within, to it not being nested.

File: lib/applicationModel.js [hunk 3]
```diff
@@ -89,54 +90,19 @@ class ApplicationModel {
...
-        debugApplicationModel(`setupModelClassMap anonymous schemas ${schemaName} type ${schema.type()}`);
-        this.registerSchemasInProperties(schema);
-        this.registerSchemasInAllOf(schema);
-      });
-      debugApplicationModel('modelClassMap:');
-      debugApplicationModel(this.modelClassMap);
-    }
-  }
-
-  registerSchemasInProperties(schema) {
```
Comment (CameronRushton) [inline lib/applicationModel.js:112]: Since we had that bug with $id, we didn't realise that some schemas were being removed from the result of allSchemas(), so this supplemented the inadequacy. Now that the issue is fixed, it's no longer required.

File: test/integration.test.js [hunk 4]
```diff
@@ -163,16 +163,6 @@ describe('template integration tests using the generator', () => {
     await assertExpectedFiles(validatedFiles);
   });
 
-  it('should generate code using schemas that have $id set', async () => {
```
Comment (CameronRushton) [inline test/integration.test.js:166]: This test is replaced with the two more robust tests below.

**Review by damaru-inc — APPROVED** [review]

**Review by damaru-inc — APPROVED** [review]
